[[initiatives]]
title = "Community Partnerships"
content = "Backing STEM outreach, civic leadership projects, and program development. This includes public showcases and creating innovative programs through dedicated training and planning initiatives."

[[initiatives]]
title = "First Lego Robotics"
content = "Promoting the development of immersive Robotics Programs within RUSD, with a strong focus on fostering inclusion, hands-on collaboration, and lasting community partnerships."

[[initiatives]]
title = "MS & HS Experience"
content = "Enhancing the day-to-day lives of middle and high school students. From funding ASB equipment to helping establish popular new clubs, we directly support the student experience."

[[initiatives]]
title = "Grant Writing"
content = "Supporting the foundation in securing vital funding through dedicated grant writing initiatives, perfectly aligned with the shared mission and vision of RSF and RUSD."

[[initiatives]]
title = "Green Solutions"
content = "Providing resources for campus Green Teams to promote environmentally conscious behaviors. We aim to develop student leadership and inspire action in sustainable green solutions."
