type = "scioly-resources"
title = "Resources for Science Olympiad"
paragraphs = [
  "This is the resources page for the Science Olympiad Coaching Program at Riverside STEM Academy, run in collaboration with Change in Scientific Importance for Youth (Delta SIFY). Our program focuses on the 23 Division B events, specifically the 17 non-build events. We will post all the resources that our coaches make for teaching on a week-by-week basis over the course of the season in a \"syllabus\" format. These resources include, but are not limited to, lecture slides, assignments, exams, and hands-on activities.",
  "Updates will be published every Monday at around 5:00 PM. While these materials are designed with in-person coaching in mind, anybody is welcome to use this content to study for the Science Olympiad season. As a disclaimer, that these are volunteer-made resources and are not affiliated with Science Olympiad.",
  "To get started, please refer to the list of events below. You can click on any specific event to see its current syllabus."
]

[[events]]
title = "Anatomy & Physiology"
link = "/scioly-resources/anatomy-and-physiology"
category = 1
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Botany"
link = "/scioly-resources/botany"
category = 1
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Disease Detectives"
link = "/scioly-resources/disease-detectives"
category = 1
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Heredity"
link = "/scioly-resources/heredity"
category = 1
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Water Quality"
link = "/scioly-resources/water-quality"
category = 1
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Dynamic Planet"
link = "/scioly-resources/dynamic-planet"
category = 2
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Meteorology"
link = "/scioly-resources/meteorology"
category = 2
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Remote Sensing"
link = "/scioly-resources/remote-sensing"
category = 2
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Rocks and Minerals"
link = "/scioly-resources/rocks-and-minerals"
category = 2
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Solar System"
link = "/scioly-resources/solar-system"
category = 2
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Circuit Lab"
link = "/scioly-resources/circuit-lab"
category = 3
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Crime Busters"
link = "/scioly-resources/crime-busters"
category = 3
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Food Science"
link = "/scioly-resources/food-science"
category = 3
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Thermodynamics"
link = "/scioly-resources/thermodynamics"
category = 3
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Codebusters"
link = "/scioly-resources/codebusters"
category = 4
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Experimental Design"
link = "/scioly-resources/experimental-design"
category = 4
sheet_id = "PLACEHOLDER_SHEET_ID"

[[events]]
title = "Write It, Do It"
link = "/scioly-resources/write-it-do-it"
category = 4
sheet_id = "PLACEHOLDER_SHEET_ID"
